# Generated by Django 3.0.4 on 2020-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booked',
            fields=[
                ('Booking_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('request_id', models.PositiveIntegerField()),
                ('userid', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=50)),
                ('user_designation', models.CharField(max_length=50)),
                ('user_mobile', models.PositiveIntegerField(max_length=10)),
                ('hall_id', models.CharField(max_length=50)),
                ('total_stage', models.PositiveIntegerField(max_length=2)),
                ('current_stage', models.PositiveIntegerField(max_length=2)),
                ('user_dept', models.CharField(max_length=50)),
                ('user_clg', models.CharField(max_length=50)),
                ('booking_date', models.DateField(default=None)),
                ('date', models.DateField()),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('function_nature', models.TextField()),
                ('additional_requirements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='hall',
            fields=[
                ('hall_incharge_id', models.CharField(max_length=50)),
                ('hall_incharge_name', models.CharField(max_length=50)),
                ('hall_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hall_name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='hod_dean',
            fields=[
                ('userid', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='principal',
            fields=[
                ('userid', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=50)),
                ('user_designation', models.CharField(max_length=50)),
                ('user_mobile', models.PositiveIntegerField(max_length=10)),
                ('hall_id', models.CharField(max_length=50)),
                ('total_stage', models.PositiveIntegerField(max_length=2)),
                ('current_stage', models.PositiveIntegerField(max_length=2)),
                ('user_dept', models.CharField(max_length=50)),
                ('user_clg', models.CharField(max_length=50)),
                ('booking_date', models.DateField(default=None)),
                ('date', models.DateField()),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('function_nature', models.TextField()),
                ('addtional_requirements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('userid', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
        migrations.AddField(
            model_name='login',
            name='userid',
            field=models.EmailField(default=None, max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
