# Generated by Django 3.0.4 on 2020-03-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200322_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='current_stage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booked',
            name='total_stage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booked',
            name='user_mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='current_stage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='total_stage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_mobile',
            field=models.CharField(max_length=10),
        ),
    ]
