# Generated by Django 3.0.4 on 2020-03-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200323_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='booked',
            name='total_stage',
        ),
        migrations.AlterField(
            model_name='request',
            name='current_stage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='total_stage',
            field=models.CharField(max_length=10),
        ),
    ]
