# Generated by Django 3.0.4 on 2020-03-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200323_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='hall_incharge_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='hall_incharge_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
