# Generated by Django 3.0.4 on 2020-03-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200329_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='End_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='booked',
            old_name='Start_time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='End_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Start_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='booked',
            name='hall_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='hall_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
