# Generated by Django 3.0.4 on 2020-04-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200403_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='addtional_requirements',
            new_name='additional_requirements',
        ),
    ]
