# Generated by Django 3.1.7 on 2021-02-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200406_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator_Incharge',
            fields=[
                ('hall_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hall_name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('generator_incharge_id', models.EmailField(max_length=254, null=True)),
                ('generator_incharge_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='booked',
            name='chief_guest_detail',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='booked',
            name='chief_guest_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='booked',
            name='dean_notes',
            field=models.TextField(default='no notes'),
        ),
        migrations.AddField(
            model_name='booked',
            name='dean_reason',
            field=models.TextField(default='no reason'),
        ),
        migrations.AddField(
            model_name='booked',
            name='generator_incharge_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booked',
            name='generator_incharge_notes',
            field=models.TextField(default='no notes'),
        ),
        migrations.AddField(
            model_name='booked',
            name='generator_incharge_reason',
            field=models.TextField(default='no reason'),
        ),
        migrations.AddField(
            model_name='booked',
            name='generator_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booked',
            name='generator_stage',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='booked',
            name='generator_text',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='booked',
            name='hall_incharge_notes',
            field=models.TextField(default='no notes'),
        ),
        migrations.AddField(
            model_name='booked',
            name='hall_incharge_reason',
            field=models.TextField(default='no reason'),
        ),
        migrations.AddField(
            model_name='booked',
            name='hod_notes',
            field=models.TextField(default='no notes'),
        ),
        migrations.AddField(
            model_name='booked',
            name='hod_reason',
            field=models.TextField(default='no reason'),
        ),
        migrations.AddField(
            model_name='booked',
            name='principal_notes',
            field=models.TextField(default='no notes'),
        ),
        migrations.AddField(
            model_name='booked',
            name='principal_reason',
            field=models.TextField(default='no reason'),
        ),
        migrations.AddField(
            model_name='request',
            name='chief_guest_detail',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='request',
            name='chief_guest_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='dean_notes',
            field=models.TextField(default='no notes'),
        ),
        migrations.AddField(
            model_name='request',
            name='dean_reason',
            field=models.TextField(default='no reason'),
        ),
        migrations.AddField(
            model_name='request',
            name='generator_incharge_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='generator_incharge_notes',
            field=models.TextField(default='no notes'),
        ),
        migrations.AddField(
            model_name='request',
            name='generator_incharge_reason',
            field=models.TextField(default='no reason'),
        ),
        migrations.AddField(
            model_name='request',
            name='generator_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='generator_stage',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='generator_text',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='request',
            name='hall_incharge_notes',
            field=models.TextField(default='no notes'),
        ),
        migrations.AddField(
            model_name='request',
            name='hall_incharge_reason',
            field=models.TextField(default='no reason'),
        ),
        migrations.AddField(
            model_name='request',
            name='hod_notes',
            field=models.TextField(default='no notes'),
        ),
        migrations.AddField(
            model_name='request',
            name='hod_reason',
            field=models.TextField(default='no reason'),
        ),
        migrations.AddField(
            model_name='request',
            name='principal_notes',
            field=models.TextField(default='no notes'),
        ),
        migrations.AddField(
            model_name='request',
            name='principal_reason',
            field=models.TextField(default='no reason'),
        ),
        migrations.AlterField(
            model_name='booked',
            name='hall_incharge_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_incharge_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='request',
            name='hall_incharge_id',
            field=models.EmailField(max_length=254),
        ),
    ]
