# Generated by Django 3.0.8 on 2021-03-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20210228_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
