# Generated by Django 3.0.8 on 2021-03-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20210316_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='request_id',
            field=models.IntegerField(),
        ),
    ]
