# Generated by Django 3.0.8 on 2021-03-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20210316_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='generator_incharge_id',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='generator_incharge_id',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
